[project]
name = "personal-expense-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.6",
    "django-widget-tweaks>=1.5.0",
    "python-decouple>=3.8",
]
